DROP TABLE IF EXISTS TBL_EMPLOYEES;
  
CREATE TABLE TBL_EMPLOYEES (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  first_name VARCHAR(250) NOT NULL,
  last_name VARCHAR(250) NOT NULL,
  email VARCHAR(250) DEFAULT NULL
);

CREATE TABLE COUNTRY (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  code VARCHAR(250) NOT NULL,
  label VARCHAR(250) DEFAULT NULL,
  currency VARCHAR(250) DEFAULT NULL,
  lang VARCHAR(250) DEFAULT NULL
);


CREATE TABLE CONTACT (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  name VARCHAR(250) DEFAULT NULL,
  phone VARCHAR(250) DEFAULT NULL,
  email VARCHAR(250) DEFAULT NULL,
   address1 VARCHAR(250) DEFAULT NULL,
    address2 VARCHAR(250) DEFAULT NULL,
     address3 VARCHAR(250) DEFAULT NULL,
      postal_Code VARCHAR(250) DEFAULT NULL,
      note VARCHAR(4000) DEFAULT NULL
  
);